name: Deploy To Live Client
'on':
  push:
    branches:
      - master
    paths:
      - projects/client/**
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build:client
      - uses: actions/upload-artifact@master
        with:
          name: public-${{ github.run_id }} # Using a unique name for the artifact
          path: ./dist/client/browser
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WHALEDROP_BOOK }}'
          target: client     # picked from targets.projectId.hosting key in .firebaserc
          channelId: live
          projectId: whaledrop-book
